### ISSUE TITLE
Need a way to ignore traits in `derive_opportunity`

### ISSUE THREAD

**Issue by smoelius** [trailofbits/dylint#1141]
Something like:
```toml
[derive_opportunity]
ignore = ["clap_derive::ValueEnum", "strum_macros::Display"]
```
