### ISSUE TITLE
`cargo dylint my_lints` produces `Error: expected more input` while parsing crate versions after updating `rustc`

### ISSUE THREAD

**Issue by PatchMixolydic** [trailofbits/dylint#19]
It seems like the error happens around here:

https://github.com/trailofbits/dylint/blob/b9002a5e8b999601326c28870b4775c5f3dfe884/dylint/src/driver_builder.rs#L107-L108

`rustc -Vv`:
```
rustc 1.54.0-nightly (5dc8789e3 2021-05-21)
binary: rustc
commit-hash: 5dc8789e300930751a78996da0fa906be5a344a2
commit-date: 2021-05-21
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

Lint library's Cargo.toml:
```toml
[package]
name = "patchmixolint"
version = "0.1.0"
authors = ["Ruby Lazuli"]
description = "Set of personal lints"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "ae0d4da764fd751494fb270fd04c2c686eac1302"}
dylint_linting = "0.1.0"
if_chain = "1.0.1"

[dev-dependencies]
dylint_testing = "0.1.0"

[package.metadata.rust-analyzer]
rustc_private = true
```
