### ISSUE TITLE
Incorrect output when two different lint libs being executed consecutively

### ISSUE THREAD

**Issue by EFanZh** [trailofbits/dylint#856]
Suppose I have two lint libraries in a workspace:

```toml
[workspace.metadata.dylint]
libraries = [{ path = "crates/my-lint-0" }, { path = "crates/my-lint-1" }]
```

If I run `cargo dylint` with these two different libraries consecutively, the second run will output the same result as the first one:

```sh
$ cargo dylint --lib my-lint-0
(some output)
$ cargo dylint --lib my-lint-1
(the same output from previous run)
```

I expect the second run should generate a different output.
